### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BenKatzman** [pusher/push-notifications-php#24]
Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in /storage/ssd3/092/4712092/public_html/pusher-push-notifications/src/PushNotifications.php:26 Stack trace: #0 /storage/ssd3/092/4712092/public_html/notify.php(5): Pusher\PushNotifications\PushNotifications->__construct(Array) #1 {main} thrown in /storage/ssd3/092/4712092/public_html/pusher-push-notifications/src/PushNotifications.php on line 26

**Comment by jonathanlloyd** [comment]
Hi! Sorry to see you're having issues.
It looks like Guzzle isn't installed - did you install this SDK using composer?

**Comment by jonathanlloyd** [comment]
I'm going to close this as it's getting a bit stale. Let me know if you're still having issues1

**Comment by reilly-freret** [comment]
Hi, I'm having this issue as well. Everything appears to be installed correctly via composer, but I get the same error as @BenKatzman
