### ISSUE TITLE
array_key_exists on php 74 and laravel

### ISSUE THREAD

**Issue by mrmmg** [pusher/push-notifications-php#29]
Hi
_In PHP 7.4 the array_key_exists is deprecated_ and when I user package to send beams this error occurred:
`ErrorException: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in C:\dev\app\Xampp\htdocs\www\projects\laravel\mrmmg\vendor\pusher\pusher-push-notifications\src\PushNotifications.php:95`
**is Any Solution to fix this?**

**Comment by mrmmg** [comment]
Hey, the #28 **Pull request** solved this issue. **I tested it and the problem is solved.** 
Please Merge that with your files and update the package.

**Comment by Humni** [comment]
This is needed - as otherwise we can't get any errors out from the SDK

**Comment by mrmmg** [comment]
In any case, in order to be able to use your package, I had to make these changes and I really do not know if it will cause problems in the future or not ...

**Comment by jonathanlloyd** [comment]
Hello all - sorry for the delay
This should now be released in v1.1.2
