### ISSUE TITLE
Laravel 8 pusher/pusher-push-notifications dependency issue with guzzlehttp/guzzle 6.0

### ISSUE THREAD

**Issue by ac-lakshmikanth** [pusher/push-notifications-php#31]
Laravel 8 installation error with "pusher-push-notifications"

pusher/pusher-push-notifications 1.1.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.

Please update to support laravel8.

**Comment by tombanksme** [comment]
Don't know if I'm supposed to put this here?

As a **temporary** fix you could forgo upgrading guzzle to ^7.0.1 or downgrade it back to ~6.0. Wouldn't recommend it in production but I took a quick look through the Laravel 8 changes and it seems that they just bumped the version guzzle version and haven't made any changes breaking changes.

**Comment by ac-lakshmikanth** [comment]
Thanks @tombanksme. 

Laravel 8 upgrade guide recommends latest guzzle version ^7.0.1 - https://laravel.com/docs/8.x/upgrade.

pusher notifications library would require to support guzzle version ^7.0.1 to enable dependent projects to upgrade to Laravel 8.

**Comment by njoyjoy** [comment]
We have run into the same issue and are blocked from upgrading to Laravel 8.  Will there be a fix for this soon - or is there a recommended work around for production environments?

**Comment by jonathanlloyd** [comment]
Hello all - I've just released v1.1.1 that supports guzzle 7
This should resolve this issue, but do let me know if you are still having problems!

**Comment by ac-lakshmikanth** [comment]
Thank you so much @jonathanlloyd . I will try latest update and post the result here.

**Comment by ac-lakshmikanth** [comment]
Latest v1.1.1 works with Laravel 8
