### ISSUE TITLE
getting error when use method

### ISSUE THREAD

**Issue by hrspndya** [pusher/push-notifications-php#34]
Fatal error: Uncaught Error: Call to undefined method Pusher\PushNotifications\PushNotifications::publishToInterests()

**Comment by ben-pusher** [comment]
Can you share the code used to invoke this? Are you passing the correct parameters to the method?

**Comment by hrspndya** [comment]
$publishResponse = $this->pushNotifications->publishToInterests(
          array('hello'),
            array('apns' => array(
                'aps' => array(
                    "content-available" => 1,
                    "data"=>array(
                        "from" => 'test_data',
                    ),
                    ),
                ),
            )
        );

**Comment by ben-pusher** [comment]
Hi, could you use double quotes in place of the single quotes?
```

$publishResponse = $this->pushNotifications->publishToInterests(
array("hello'),
array("apns" => array(
"aps" => array(
"content-available" => 1,
"data"=>array(
"from" => "test_data",
),
),
),
)
);

```

**Comment by ben-pusher** [comment]
This has been inactive for a week now, I will close this issue. If you still need support please contact us at https://support.pusher.com/hc/en-us/requests/new
