### ISSUE TITLE
Updated composer.json to support firebase/php-jwt ^6

### ISSUE THREAD

**Issue by mojowill** [pusher/push-notifications-php#37]
Version 6 of PHP-JWT is now released and the recommended version, is it possible to get this tested and bumped up as was done with Guzzle? We are currently unable to use due to a conflict.

`pusher/pusher-push-notifications[1.1.1, ..., 1.1.2] require firebase/php-jwt ^5.0 -> found firebase/php-jwt[v5.0.0, ..., v5.5.1] but it conflicts with your root composer.json require (^6.0).`

**Comment by mo7amedmamdouh** [comment]
I opened a PR for it https://github.com/pusher/push-notifications-php/pull/38 cc @jonathanlloyd

**Comment by benjamin-tang-pusher** [comment]
We're also going to have to migrate this repo away from travis to github action, as I can't run tests on it (as you can tell, this repo hasn't been updated in a while). I'm trying to get one of the engineers to prioritise it, or I might be able to do it.

**Comment by danharrin** [comment]
This has been fixed by #39 and can now be closed
