### ISSUE TITLE
Endpoint

### ISSUE THREAD

**Issue by chris-redbeed** [pusher/push-notifications-php#6]
Hello,

maybe you can add `endpoint` option here:
https://docs.pusher.com/push-notifications/reference/server-sdk-php#connecting-to-pusher

For me its only works with the correct endpoint.

btw. i like the new API (simple and clean) +1

**Comment by turingincomplete** [comment]
The endpoint parameter should now configure itself automatically: https://github.com/pusher/push-notifications-php/commit/c13dbdbaf31a1395be623e649bf9ea3a476bde69

Hopefully this should obviate the need for overriding it.

Thanks for the feedback!

**Comment by turingincomplete** [comment]
You can update to 0.9.1 for this change :)
